; generated by BambuStudio 1.9.0
; model name: cable_clip_v3
; total height: 38.0
;MAX_LAYER_Z:38.0
M109 S215 ; wait nozzle
M190 S60
G28
G1 Z0.2 F600
G1 X50 Y50 Z0.2 F3000
G1 X150 Y50 E8 F2000
G1 X150 Y150 E16
G1 Z0.4
; layers...
G1 Z37.6
G1 Z38.0
M104 S0
M140 S0
M84
