; generated by OrcaSlicer 2.1.0
; model name: phone_stand
; total height: 15.2
;MAX_LAYER_Z:15.2
G28 ; home all axes
G1 Z0.2 F600
M104 S220 ; set nozzle temp
M190 S65  ; wait bed temp
G1 X10 Y10 Z0.2 F3000
; --- layer 1 ---
G1 X100 Y10 E5 F1800
G1 X100 Y100 E10
G1 X10 Y100 E15
G1 Z0.4
; ... (layers continue)
G1 Z15.0
G1 Z15.2
M104 S0
M140 S0
M84
