; generated by PrusaSlicer 2.8.0
; model name: spiral_vase
; total height: 62.4
;MAX_LAYER_Z:62.4
M104 S215
M190 S55
G28
G1 Z0.3 F400
G1 X80 Y80 F4000
G1 X80 Y80 Z0.3 E0.5 F1200
; spiral vase mode
G1 X180 Y80 Z0.6 E5
G1 X180 Y180 Z0.9 E10
G1 X80 Y180 Z1.2 E15
G1 X80 Y80 Z1.5 E20
; continues...
G1 Z61.8
G1 Z62.4
M104 S0
M140 S0
M84
